### ISSUE TITLE
Add flask-file-upload

### ISSUE THREAD

**Issue by joegasewicz** [mjhea0/awesome-flask#5]
Can I Add flask-file-upload? Not sure how this works but do i create a PR or do you guys handle additions? thanks very much, Joe.

https://github.com/joegasewicz/flask-file-upload

**Comment by mjhea0** [comment]
Yes, please add a PR. Thanks!

**Comment by joegasewicz** [comment]
> Yes, please add a PR. Thanks!

Thanks @mjhea0

**Comment by joegasewicz** [comment]
@mjhea0 I tried to push up commits on a branch called `flask-file-upload` seems like i dont have perms, thank you ;O)

**Comment by mjhea0** [comment]
You need to fork, make the changes on your fork, push them up to your remote, then open the PR.
