### ISSUE TITLE
Add Flask-JWT-Router

### ISSUE THREAD

**Issue by joegasewicz** [mjhea0/awesome-flask#6]
Please could I add Flask-JWT-Router to your project:

https://github.com/joegasewicz/flask-jwt-router

**Comment by joegasewicz** [comment]
Tried to push on a branch called `flask_jwt_router` is this correct as I don't have perms on your repo, thank you very much, Joe.

**Comment by mjhea0** [comment]
See https://github.com/mjhea0/awesome-flask/issues/5#issuecomment-572585223. :)
